### ISSUE TITLE
let symbol satisfy encoding.TextMarshaler and encoding.TextUnmarshaler

### ISSUE THREAD

**Issue by nightlyone** [spakin/intern#1]
It would be great, if symbol could satisfy the [TextMarshaler](http://godoc.org/encoding#TextMarshaler) and [TextUnmarshaler](http://godoc.org/encoding#TextUnmarshaler) interfaces.

This allows to use the symbol as drop-in-replacement in strings which will be JSON and XML encoded. 

This would also allow other optimizations avoiding the creation of such strings later using  the `m[string(byteSlice)]` lookup optimizations of later Go releases.

**Comment by spakin** [comment]
I should be able to do that.  As far as I can tell, though, I'd need to implement [TextMarshaler](https://golang.org/pkg/encoding/#TextMarshaler) and [TextUnmarshaler](https://golang.org/pkg/encoding/#TextUnmarshaler) on `*intern.Eq` and `*intern.LGE` (i.e., pointers to the symbols, not the symbols themselves).  Does that sound correct?

If so, it does imply that symbols aren't *exactly* a drop-in replacement as you'd have to replace a value type `string` with a reference type `*intern.Eq` or `*intern.LGE`.  But if that's okay, I can go ahead and implement the two interfaces.
